# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Laudelino/SkyDrive/Estudos/UTFPR/9th/TCC2/Proj/V144D/20160702/KalmanProject/vhdl/vivado/KalmanProject.srcs/sources_1/ip/PLPS_FIFO/PLPS_FIFO.xci
# IP: The module: 'PLPS_FIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Laudelino/SkyDrive/Estudos/UTFPR/9th/TCC2/Proj/V144D/20160702/KalmanProject/vhdl/vivado/KalmanProject.srcs/sources_1/ip/PLPS_FIFO/PLPS_FIFO/PLPS_FIFO_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLPS_FIFO'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Laudelino/SkyDrive/Estudos/UTFPR/9th/TCC2/Proj/V144D/20160702/KalmanProject/vhdl/vivado/KalmanProject.srcs/sources_1/ip/PLPS_FIFO/PLPS_FIFO/PLPS_FIFO.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLPS_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Laudelino/SkyDrive/Estudos/UTFPR/9th/TCC2/Proj/V144D/20160702/KalmanProject/vhdl/vivado/KalmanProject.srcs/sources_1/ip/PLPS_FIFO/PLPS_FIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLPS_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/Laudelino/SkyDrive/Estudos/UTFPR/9th/TCC2/Proj/V144D/20160702/KalmanProject/vhdl/vivado/KalmanProject.srcs/sources_1/ip/PLPS_FIFO/PLPS_FIFO.xci
# IP: The module: 'PLPS_FIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Laudelino/SkyDrive/Estudos/UTFPR/9th/TCC2/Proj/V144D/20160702/KalmanProject/vhdl/vivado/KalmanProject.srcs/sources_1/ip/PLPS_FIFO/PLPS_FIFO/PLPS_FIFO_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLPS_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Laudelino/SkyDrive/Estudos/UTFPR/9th/TCC2/Proj/V144D/20160702/KalmanProject/vhdl/vivado/KalmanProject.srcs/sources_1/ip/PLPS_FIFO/PLPS_FIFO/PLPS_FIFO.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLPS_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Laudelino/SkyDrive/Estudos/UTFPR/9th/TCC2/Proj/V144D/20160702/KalmanProject/vhdl/vivado/KalmanProject.srcs/sources_1/ip/PLPS_FIFO/PLPS_FIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLPS_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
